### ISSUE TITLE
"STAND SPONSORLARI"

### ISSUE THREAD

**Issue by mstfknn** [Octosec/hacktrick_web_app#49]
"Game of Pwners Sponsorları" olmalı.

**Comment by mfeminer** [comment]
sadece ön tarafta görünen ad mı değişecek?

**Comment by mstfknn** [comment]
@mfeminer evet kanki o değişse yeter

**Comment by MertcanGokgoz** [comment]
Tamamlandı. https://github.com/Octosec/hacktrick_web_app/pull/59
