### ISSUE TITLE
js dialogbox 

### ISSUE THREAD

**Issue by mstfknn** [Octosec/hacktrick_web_app#60]
Okudum onaylıyorum. Kutusu.

**Comment by mstfknn** [comment]
@MertcanGokgoz gel bakem

**Comment by MertcanGokgoz** [comment]
Eğitim Seçimi için "Okudum, Onaylıyorum" gibi bir checkbox için kullanılacak bir Dialogbox kullanalım düşüncesindeyim.

Örnek

https://jqueryui.com/dialog/#animated
